### ISSUE TITLE
dump publishes private rooms

### ISSUE THREAD

**Issue by localguru** [Flipez/hubot-rss-rolf#1]
Hi,

via ```rss dump``` it is possible to get names of private rooms in RocketChat, which is to my mind a kind of security risk as private room names are hidden to others.

Ciao
Marcus

**Comment by Flipez** [comment]
Hi Marcus,

thanks for the notification!

I think this specific command isn't useful anyway so I'll remove it in the next version.

**Comment by localguru** [comment]
Hi Robert,

or a new ENV var as a list something like

```HUBOT_RSS_DUMP_USER="username1, username2"```

which limits the dump command to a list of users.

Ciao!

**Comment by Flipez** [comment]
@localguru I've removed the command and published the fix with version 1.1.1 to npm.

Let me know if you would like to change the dump behavior or feel free to create a PR.

**Comment by localguru** [comment]
Is there another way to find out what feeds Rolf stored to brain?

**Comment by localguru** [comment]
see https://github.com/Flipez/hubot-rss-rolf/pull/4
