### ISSUE TITLE
Save rss urls on stop/restart

### ISSUE THREAD

**Issue by pcmerc** [Flipez/hubot-rss-rolf#12]
In testing it appears that stopping the bot & starting/restarting causes all rss urls to be lost. Is there a way to save these prior?

**Comment by Flipez** [comment]
@pcmerc This should be done by your hubot-brain (for example the redis-brain). If you use a brain inside docker make sure you map the date with a volume to the host.

**Comment by pcmerc** [comment]
I'm not using the docker container.

**Comment by Flipez** [comment]
But you need some kind of hubot-brain. Are you using one?

**Comment by pcmerc** [comment]
I do have "hubot-redis-brain": "^1.0.0",

**Comment by pcmerc** [comment]
Ok, I see what's possibly missing. I need to add some configuration data for hubot-brain-redis.
Thanks for pointing me in a direction, Flipez.

**Comment by Flipez** [comment]
You're welcome.

Let me know if you think there is an issue with rolf ;)
