### ISSUE TITLE
deleting feeds with a trailing slash

### ISSUE THREAD

**Issue by localguru** [Flipez/hubot-rss-rolf#2]
Hi Robert,

I had some problems today to remove an URL which I added with a trailing slash. RocketChat doesn't display a trailing slash and ```rss list``` doesn't show it. So if you want to delete the URL later and don't remember the trailing slash the URL is not found ;)

   See here: https://github.com/RocketChat/Rocket.Chat/issues/7527

I would classify this as a RocketChat problem, but if deleting an URL  a workaround could be to test both versions of an URL with and without a trailing slash.

Ciao!

**Comment by Flipez** [comment]
@localguru I've fixed the check and it should now delete both with and without the trailing slash.

The fix is published with version 1.1.1 to npm

Due to the lack of tests please let me know if this works :thinking: 

Also I'am *very* new to coffeescript so this might not the best fix. PRs welcome

**Comment by localguru** [comment]
@Flipez Thanks, Robert! :+1: I will test and give you feedback.

**Comment by localguru** [comment]
It's working perfectly, nice! :1st_place_medal:
